# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeclasses', '0010_delete_old_player_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultAccount',
        ),
        migrations.DeleteModel(
            name='DefaultCharacter',
        ),
        migrations.DeleteModel(
            name='DefaultExit',
        ),
        migrations.DeleteModel(
            name='DefaultGuest',
        ),
        migrations.DeleteModel(
            name='DefaultObject',
        ),
        migrations.DeleteModel(
            name='DefaultRoom',
        ),
        migrations.DeleteModel(
            name='DefaultScript',
        ),
        migrations.DeleteModel(
            name='DoNothing',
        ),
        migrations.DeleteModel(
            name='ScriptBase',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
