version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build container
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t seanbrandt/evennia:$CIRCLE_BRANCH .

      - run: docker push seanbrandt/evennia:$CIRCLE_BRANCH

