version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build container
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build --build-arg BUILD_VERSION="${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)" \
              -t seanbrandt/evennia:${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7) .
            docker build -t seanbrandt/evennia:${CIRCLE_BRANCH} .

      - run:
          name: push images
          command: |
            docker push seanbrandt/evennia:${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)
            docker push seanbrandt/evennia:${CIRCLE_BRANCH}

