# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0015_auto_20170706_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeldb',
            name='db_subscriptions',
        ),
    ]
