# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_remove_scriptdb_db_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptdb',
            name='db_account',
            field=models.ForeignKey(blank=True, help_text=b'the account to store this script on (should not be set if db_obj is set)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'scripted account'),
        ),
    ]
