# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_copy_player_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdb',
            name='db_is_connected',
            field=models.BooleanField(default=False, help_text=b'If player is connected to game or not', verbose_name=b'is_connected'),
        ),
    ]
